# Generated by Django 4.2.5 on 2023-09-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("url_short", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "kirr_url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="url_short.urlshort",
                    ),
                ),
            ],
        ),
    ]
